### PR TITLE
LGA-649: Remove template-deploy code

### PR DESCRIPTION
**Pull request by sldblog**
## What does this pull request do?

This pull request removes the remnants of template-deploy-related branching in the codebase.

## Any other changes that would benefit highlighting?

Please review changes commit-by-commit for further details.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title."

### CODE REVIEW

**Comment by sldblog** [comment]
Superset of #142 (that can go first).

**Comment by sldblog** [comment]
Sorry for not opening the pull request earlier 🙇 😭

**Comment by said-moj** [comment]
> Superset of #142 (that can go first).

Can we merge this PR and close #142

**Comment by sldblog** [comment]
✅ Tested on staging, upload and API both work fine.

**Pull request merged**
